language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env:
  global:
  - secure: WvLPkmUdSrFj3n3qrnRhSRxvxTq61ongt3XQMbvcEGUN6R4YfO2wgeRjE7bgWgq0tRRCWTNP/phYZZzsZPuOGHrkZDFMh8fz6/9zRYC23WbuSzV4mOorjGtQ2F3bdI6DhpQnuoNCm/5KMumzU3gMYJG5215CEZBLKAhjtjCk8wota5sCzOjGvpTySxCScjHNPUQhOwtqjBTWZ5tCOcYTxxUkLIDNo3Z7ZFwntjuMbhWr99xMn/maC0J2XbOaE+BDID24XvlttUDSTWZTZdT9Q4M0eJA/UOgrLk/duq/ocKeFPvDxYp6FY2ohuY6xiavyMksCFqQiGd0QhZTOWAcywA9M1IQip40uzI+ywyvWQAhTQQroqLlbgApDxJg8auhqLncYZgaYVyClWJPtQUvVvB/aN5h0a4W3iMm8N5GHI7fxWfjmneAyJpaEtotDzoJ/iXhRye4pCphl4cdofDsShGE5yN2I30RNUpl7l3JnVsADPPdEuJEN4jG7o6d57P2mT/rlncRzRowaYYKmiJ37b25IhTq2/IzIwAmSeHe15tPodNLHwHFVOnTSNR4bGc4QeYwok+5bJOUHPos5v9dLhTUl7BBPhP0rbOLUBz5q14nrxhiEVKBOjbny9oIeay9zEDhWgZZ/y1KO3935RXyJfesQ2DPUuhyFJtLVCvmOUvc=
  itJxZ40IjpXs/vRzqraQ0MtUO0KNvLuFmNNZyjkWzqTIWM728pzVCjvgvfWYr/bIxgJWtCPKpQy7bPDjBkepel4NNTmVlUhlalL9k/+5WNFqZRfprORfjsfFK2e1dUhuMz3VWiK+QoM7LenPFfmxZAWCgi3ifhNdwFLIVVppXF4USjcVPZF4ghxhuoZzu6dyuESNmMmvWraszJXDC7+OSTuvENw8rQbT0F+b84ik3Etz2sO9J/7O6if8/BPDJHFCF1iVsh8kqxugJxwRRuImrO8CM3EhsJotU3IkoHKCGhVi3cEfxOz2qhyHmXrWxRqtUdgXpV9nqIgCQWaEHTh75izp9xpHx8lENhhqJWrBFUL9sAJA90acXWniSl4M7spsDsmJOgKNAKdwNZL70wr+pujy4xxOlbatVKP81qwo0FYucJC3ldUvc5zqlluA1nLx7F88RtyDkTOAaEmhake+kdd+CfjZAIYSKXyIKQTFoABxAneLbcFhkgDLpiJJOyFMhFsc4/K9H2QwyACqFuSu64Xo/n0JO6MGfhC0NKICMoZbdgy9uBf0PR5AD8Syq5BynC2mdI6mPznXiZIDBlE5LB9SdnLNxwlWX8KdQ6JLu0sftBdAPtVmFO7JyhRdaH+a4EEeln0AwbZUgm71gFhJX0v41i68lXdBMpfUS5CUvLg=
deploy:
  provider: heroku
  api_key:
    secure: JY7llOJE9GyChO77MkEj+0Ci3CvA6en3FwOvi2ng0rKzFT8Wr/PnPxnESsFfD274c6I2ZalShEOhpYhtU+feM/yESxTzDnrFykkC02Ph2Rk0/nT/Y22lxuKC2OJIPaTs98bfOhNZP67zaAyhuPmguuRaQhHskIOtNaVMcQoGpaKTTcbqOKYc47yixqJSl4lX8H1mpywgMrqAoohS6pmhswN2N4iihRrhIgR/CbOSXX79RGqT209MwdUncSuY3C3mb/fCudzTfIZUBkSD9eaZO6IDOxLsZURtMJNKH69bMGe0doMg4xVDLpVypHDX+c0DV2dfZQPXSw7g+4SuCC42L8cy2AGYX8cq84RBkA0aZWmMx9dch9I6hwDNzERN03XV3DSoa/6tjj5Qb9PJjZF5K4WJYkmuPi/9/W0Olmz9zy3LfRxewjQP8ngV+k1Wyg98H1Gw+V6N123iyt9yOsmZz0r+pxjYJ4AHJplq0chuYFK0cTXryA0gxoxflRjCcxNSahIFKnaieoAO2g2rO0jzQsrGAKuxoDQitHqrtQhQFcg26Mt3KHa39sJVTttyhZvwe43u+WvwaL7WfVgI7MkInRcvnrm96wmcXaf5b+o+wxPrXhT/fvv7hzFBHc5GDyrNhpwB1zATnJL0HWXb3f/3j3OWre/t8G3l8adpRPZSNhE=
  app: viewing-party-1
  on:
    repo: josephbudina/viewing_party
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
  api_key--com:
    secure: HG2xpEBIS0OGqgMpNYjT6fU09ezt63Arx0TXJNoreow31uTfaH7B1QVtZUnavrLXSAnbggcEzNADDL+Rzp8d0jnYqEx8FhLE9IISSrR1dNNfTSWITc8UIR2dIG4Gmefa96i3zxJxP+ng3/uVugDFfCsnKTXWt9XbxzCOG02cC+1AAI5pbS5GJZLCspiX5AaviOqSjJvpKXnfmZq81IHgkHiCNSyM0CNt7DAAa1GpmGKYpbhnUCTMdny3brXEhYmK1LRFpt9eyajboljcxDdfPP0gs+2Vz0LiOVclIPOVVvIQHrK1Pujxf94W0vfBk8K4PfXuq+yhx32gO1sQRrNolVumUwebOaSS/4A7QVQT0hvRExkO2c07Zm/rmentu2EFCRLo3p9P2iiJJLcB25160i/ucuXwLoubTKhqNyBkOElCoDqpiVvcHFRUaL+lpus5qkVyyTefnjjiZDdbwdA18CUSuqvoAISqEZb4Oc3tkQiTJHQJ9wvtGMaOt0bDN9KnyG1ID8c7acxI8ctNcYoHXurWoNWO1On5TK9f/smPx0VdCOshmNdgWIjd7fHMQowU7XyeNfBTMXvOCGWsqvuFNDNF3Tcn64nCpaa986WvBTQUAOi4R5j+yyfniu06C/QmabE4VmynjPutbpeTQZfDURNFAgyDIij3VsY9iNuDt+4=
