language: ruby
rbenv:
- 2.5.3
cache:
  - bundler
  - yarn
addons:
  postgresql: 9.6
before_install:
  - nvm install --lts
  - gem install bundler: 2.1.4
before_script:
  - yarn
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate
env:
  global:
  - secure: WvLPkmUdSrFj3n3qrnRhSRxvxTq61ongt3XQMbvcEGUN6R4YfO2wgeRjE7bgWgq0tRRCWTNP/phYZZzsZPuOGHrkZDFMh8fz6/9zRYC23WbuSzV4mOorjGtQ2F3bdI6DhpQnuoNCm/5KMumzU3gMYJG5215CEZBLKAhjtjCk8wota5sCzOjGvpTySxCScjHNPUQhOwtqjBTWZ5tCOcYTxxUkLIDNo3Z7ZFwntjuMbhWr99xMn/maC0J2XbOaE+BDID24XvlttUDSTWZTZdT9Q4M0eJA/UOgrLk/duq/ocKeFPvDxYp6FY2ohuY6xiavyMksCFqQiGd0QhZTOWAcywA9M1IQip40uzI+ywyvWQAhTQQroqLlbgApDxJg8auhqLncYZgaYVyClWJPtQUvVvB/aN5h0a4W3iMm8N5GHI7fxWfjmneAyJpaEtotDzoJ/iXhRye4pCphl4cdofDsShGE5yN2I30RNUpl7l3JnVsADPPdEuJEN4jG7o6d57P2mT/rlncRzRowaYYKmiJ37b25IhTq2/IzIwAmSeHe15tPodNLHwHFVOnTSNR4bGc4QeYwok+5bJOUHPos5v9dLhTUl7BBPhP0rbOLUBz5q14nrxhiEVKBOjbny9oIeay9zEDhWgZZ/y1KO3935RXyJfesQ2DPUuhyFJtLVCvmOUvc=
  - secure: itJxZ40IjpXs/vRzqraQ0MtUO0KNvLuFmNNZyjkWzqTIWM728pzVCjvgvfWYr/bIxgJWtCPKpQy7bPDjBkepel4NNTmVlUhlalL9k/+5WNFqZRfprORfjsfFK2e1dUhuMz3VWiK+QoM7LenPFfmxZAWCgi3ifhNdwFLIVVppXF4USjcVPZF4ghxhuoZzu6dyuESNmMmvWraszJXDC7+OSTuvENw8rQbT0F+b84ik3Etz2sO9J/7O6if8/BPDJHFCF1iVsh8kqxugJxwRRuImrO8CM3EhsJotU3IkoHKCGhVi3cEfxOz2qhyHmXrWxRqtUdgXpV9nqIgCQWaEHTh75izp9xpHx8lENhhqJWrBFUL9sAJA90acXWniSl4M7spsDsmJOgKNAKdwNZL70wr+pujy4xxOlbatVKP81qwo0FYucJC3ldUvc5zqlluA1nLx7F88RtyDkTOAaEmhake+kdd+CfjZAIYSKXyIKQTFoABxAneLbcFhkgDLpiJJOyFMhFsc4/K9H2QwyACqFuSu64Xo/n0JO6MGfhC0NKICMoZbdgy9uBf0PR5AD8Syq5BynC2mdI6mPznXiZIDBlE5LB9SdnLNxwlWX8KdQ6JLu0sftBdAPtVmFO7JyhRdaH+a4EEeln0AwbZUgm71gFhJX0v41i68lXdBMpfUS5CUvLg=
